image: jelaniwoods/appdev2021-base-ruby@sha256:1206e277e3d145cf9b90339089b26f866cfa59d5cf6e3d8b1973a346944c9e5e

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 4567
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced
    - vortizhe.simple-ruby-erb
    - CraigMaslowski.erb
    - Vense.rails-snippets
    - wingrunr21.vscode-ruby
